package com.condominio.novaalianca.dto.inter.cobranca.enums;

public enum CodigoDesconto {
    NAOTEMDESCONTO,
    VALORFIXODATAINFORMADA,
    PERCENTUALDATAINFORMADA,
    VALORANTECIPACAO_DIA,
    VALORANTECIPACAO_DIAUTIL,
    PERCENTUALANTECIPACAO_DIA,
    PERCENTUALANTECIPACAO_DIAUTIL
}
