server.port=8086
logging.level.web=DEBUG
spring.devtools.add-properties=false

spring.jpa.open-in-view=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.generate-ddl = true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true







spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true




##Paramentros para Acesar a API do Banco Inter
banco.inter.url.boleto:https://cdpj.partners.bancointer.com.br/cobranca/v2/boletos
banco.inter.url.token:https://cdpj.partners.bancointer.com.br/oauth/v2/token
banco.inter.url.extrato:https://cdpj.partners.bancointer.com.br/banking/v2/extrato


##PARAMETROS COMUNICACAO BANCO INTER
boleto.cpfcnpj.benificiario : 07890271000109
boleto.numerocontacorrente : 45553602
banco.inter.caminho.certificado : ${caminho.certificado.condominio:src/main/resources/certs/CONDOMINIONOVAALIANCA.pfx}
banco.inter.senha.certificado : ${senha.certificado.condominio:140908}
banco.inter.client.id: ${client.id:4f7275a8-d3fe-4c70-a05d-84dae5f7cea0}
banco.inter.client.secret: ${client.secret:4b65c184-8368-4001-90cd-498f522337bf}
banco.inter.grant.type:${grant.type:client_credentials}


##Paramentros para Envio de Email
mail.from : Condominio Nova Alianca <condominionovaaliancasbc@gmail.com>
spring.mail.host=smtp.gmail.com
spring.mail.username=${username.gmail.condominio:condominionovaaliancasbc}
spring.mail.password=${senha.gmail.condominio:xuvjwatpamgpaywy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.port=587

##ParaMETROS DOCKER
source.docker=${DOCKER:false}