server.port=8086
#logging.level.web=DEBUG
#spring.devtools.add-properties=false
spring.datasource.url=${DB_URL:jdbc:postgresql://192.168.15.10:5432/condominio}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:140908}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO




#
#spring.jpa.generate-ddl=true
#spring.sql.init.mode=always
#
#

#
#spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#
#
#
#
#
#
##Paramentros para Acesar a API do Banco Inter
banco.interurl.path_prod:https://cdpj.partners.bancointer.com.br
banco.interurl.path_sand:https://cdpj-sandbox.partners.uatinter.co
banco.inter.url.boleto:/cobranca/v3/cobrancas
banco.inter.url.token:/oauth/v2/token
banco.inter.url.extrato:/banking/v2/extrato
#
boleto.cpfcnpj.benificiario : 07890271000109
boleto.numerocontacorrente : 45553602
banco.inter.caminho.certificado : ${INTER_CERT_PATH:${caminho.certificado.condominio:src/main/resources/certs/CONDOMINIONOVAALIANCA.pfx}}
banco.inter.senha.certificado : ${INTER_CERT_PASSWORD:${senha.certificado.condominio:140908}}
#banco.inter.client.id: ${client.id:4f7275a8-d3fe-4c70-a05d-84dae5f7cea0}
#banco.inter.client.secret: ${client.secret:4b65c184-8368-4001-90cd-498f522337bf}
banco.inter.client.id: ${INTER_CLIENT_ID:${client.id:61851b55-cd4c-4932-bfb4-0b38ea941aad}}
banco.inter.client.secret: ${INTER_CLIENT_SECRET:${client.secret:87c6f9e2-e497-4611-bd98-d55b0ea085be}}
banco.inter.grant.type:${grant.type:client_credentials}
spring.jpa.open-in-view=true
#
##Paramentros para Envio de Email
mail.from : Condominio Nova Alianca <condominionovaaliancasbc@gmail.com>
spring.mail.host=smtp.gmail.com
spring.mail.username=${MAIL_USERNAME:${username.gmail.condominio:condominionovaaliancasbc}}
spring.mail.password=${MAIL_PASSWORD:${senha.gmail.condominio:xuvjwatpamgpaywy}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.port=587


source.docker=${DOCKER:false}
