server.port=8086
source.docker=${DOCKER:false}
#logging.level.web=DEBUG
#spring.devtools.add-properties=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO




#
#spring.jpa.generate-ddl=true
#spring.sql.init.mode=always
#
#

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#
##Paramentros para Acesar a API do Banco Inter
banco.interurl.path_prod:https://cdpj.partners.bancointer.com.br
banco.interurl.path_sand:https://cdpj-sandbox.partners.uatinter.co
banco.inter.url.boleto:/cobranca/v3/cobrancas
banco.inter.url.token:/oauth/v2/token
banco.inter.url.extrato:/banking/v2/extrato

spring.jpa.open-in-view=true

# Configurações de agendamento (Cron)
cron.schedule.valida-envio=0 */4 10 1 * *
cron.schedule.recupera-boleto=0 */1 10 1 * *
cron.schedule.envia-email=10 */2 10 1 * *
cron.schedule.extrato=0 */10 * * * *
