spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.jpa.open-in-view=false
security.oauth2.client.client-id=${OAUTH_CLIENT_ID}
security.oauth2.client.client-secret=${OAUTH_CLIENT_SECRET}
jwt.secret=${JWT_SECRET}
jwt.duration=${JWT_DURATION}
cors.origins=${CORS_ORIGINS}

##BANCOINTER
banco.inter.client.id=${INTER_CLIENT_ID}
banco.inter.client.secret=${INTER_CLIENT_SECRET}
banco.inter.grant.type=${INTER_GRANT_TYPE:client_credentials}

boleto.cpfcnpj.benificiario : 07890271000109
boleto.numerocontacorrente : 45553602
banco.inter.caminho.certificado=${INTER_CERT_PATH:src/main/resources/certs/CONDOMINIONOVAALIANCA.pfx}
banco.inter.senha.certificado=${INTER_CERT_PASSWORD}

##Paramentros para Envio de Email
mail.from : Condominio Nova Alianca <condominionovaaliancasbc@gmail.com>
spring.mail.host=smtp.gmail.com
spring.mail.username=${MAIL_USERNAME:condominionovaaliancasbc}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.port=587

##Confiigurações do Spring data
spring.datasource.url=${DB_URL_DEV}
spring.datasource.username=${DB_USERNAME_DEV}
spring.datasource.password=${DB_PASSWORD_DEV}



